W0427 17:32:38.692955 2847673 torch/distributed/run.py:793] 
W0427 17:32:38.692955 2847673 torch/distributed/run.py:793] *****************************************
W0427 17:32:38.692955 2847673 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0427 17:32:38.692955 2847673 torch/distributed/run.py:793] *****************************************
W0427 17:32:41.176455 2847673 torch/distributed/elastic/agent/server/api.py:704] Received Signals.SIGINT death signal, shutting down workers
W0427 17:32:41.177104 2847673 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2847701 closing signal SIGINT
W0427 17:32:41.177273 2847673 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2847702 closing signal SIGINT
Traceback (most recent call last):
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 181, in <module>
    main(parse_args())
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 67, in main
    graph = KnowledgeGraph(cfg.data.data_path)
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/data.py", line 25, in __init__
    self.id2entity[int(id)] = entity
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 181, in <module>
    main(parse_args())
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 67, in main
    graph = KnowledgeGraph(cfg.data.data_path)
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/data.py", line 25, in __init__
    self.id2entity[int(id)] = entity
KeyboardInterrupt
W0427 17:32:41.381997 2847673 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2847701 closing signal SIGTERM
W0427 17:32:41.382331 2847673 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2847702 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 696, in run
    result = self._invoke_run(role)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 855, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 84, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 2847673 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emma/polly_env_py39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 260, in launch_agent
    result = agent.run()
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 137, in wrapper
    result = f(*args, **kwargs)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in run
    self._shutdown(e.sigval)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 365, in _shutdown
    self._pcontext.close(death_sig)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 572, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 909, in _close
    handler.proc.wait(time_to_wait)
  File "/usr/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1927, in _wait
    time.sleep(delay)
  File "/home/emma/polly_env_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 84, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 2847673 got signal: 2
